// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using speaklis_fullend.Models;

namespace speaklis_fullend.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("speaklis_fullend.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int?>("RoleId");

                    b.Property<string>("SecondName");

                    b.Property<string>("SurName");

                    b.Property<int?>("TypeAccountId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TypeAccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("speaklis_fullend.Models.AccountTags", b =>
                {
                    b.Property<int?>("AccountId");

                    b.Property<int?>("TagsId");

                    b.HasKey("AccountId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("AccountTags");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Billing.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CteateTime");

                    b.Property<Guid>("Uid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Billing.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContractId");

                    b.Property<int?>("PaymentTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Billing.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Fax");

                    b.Property<int>("Inn");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<DateTime>("BegTime");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Name");

                    b.Property<int?>("StatusId");

                    b.Property<int?>("SubsrubeId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubsrubeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("speaklis_fullend.Models.RoomTags", b =>
                {
                    b.Property<int?>("RoomId");

                    b.Property<int?>("TagsId");

                    b.HasKey("RoomId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RoomTags");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Subsrube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Subscrubes");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("speaklis_fullend.Models.TypeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeAccounts");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Account", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Company", "Company")
                        .WithMany("Accounts")
                        .HasForeignKey("CompanyId");

                    b.HasOne("speaklis_fullend.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("speaklis_fullend.Models.TypeAccount", "TypeAccount")
                        .WithMany("Accounts")
                        .HasForeignKey("TypeAccountId");
                });

            modelBuilder.Entity("speaklis_fullend.Models.AccountTags", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Account", "Account")
                        .WithMany("AccountTags")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("speaklis_fullend.Models.Tags", "Tags")
                        .WithMany("AccountTags")
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("speaklis_fullend.Models.Avatar", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Account", "Account")
                        .WithOne("Avatar")
                        .HasForeignKey("speaklis_fullend.Models.Avatar", "AccountId");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Billing.Contract", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Account", "Account")
                        .WithOne("Contract")
                        .HasForeignKey("speaklis_fullend.Models.Billing.Contract", "AccountId");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Billing.Payment", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Billing.Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId");

                    b.HasOne("speaklis_fullend.Models.Billing.PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId");
                });

            modelBuilder.Entity("speaklis_fullend.Models.Room", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Account", "Account")
                        .WithMany("Rooms")
                        .HasForeignKey("AccountId");

                    b.HasOne("speaklis_fullend.Models.Status", "Status")
                        .WithMany("Rooms")
                        .HasForeignKey("StatusId");

                    b.HasOne("speaklis_fullend.Models.Subsrube")
                        .WithMany("Rooms")
                        .HasForeignKey("SubsrubeId");
                });

            modelBuilder.Entity("speaklis_fullend.Models.RoomTags", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Room", "Room")
                        .WithMany("RoomTags")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("speaklis_fullend.Models.Tags", "Tags")
                        .WithMany("RoomTags")
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("speaklis_fullend.Models.Subsrube", b =>
                {
                    b.HasOne("speaklis_fullend.Models.Account", "Account")
                        .WithOne("Subsrube")
                        .HasForeignKey("speaklis_fullend.Models.Subsrube", "AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
